In [1]:
import numpy as np

In [5]:
matris = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
matris.shape

(3, 3)

In [9]:
matris2 = matris

In [10]:
matris2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matris[1,1] = 150

In [13]:
matris

array([[  1,   2,   3],
       [  4, 150,   6],
       [  7,   8,   9]])

In [14]:
matris2

array([[  1,   2,   3],
       [  4, 150,   6],
       [  7,   8,   9]])

In [15]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
m2 = m1.copy()

In [18]:
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
m1[1,1] = 150

In [21]:
m1

array([[  1,   2,   3],
       [  4, 150,   6],
       [  7,   8,   9]])

In [22]:
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
m3 = np.arange(0,10,2) # Sıfırdan, on'a, ikişer

In [24]:
m3

array([0, 2, 4, 6, 8])

In [25]:
m4 = np.arange(5,73,4)

In [26]:
m4

array([ 5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69])

In [33]:
m5 = np.random.rand(2,2)

In [34]:
m5

array([[0.20282401, 0.57426597],
       [0.29158038, 0.72847412]])