In [4]:
liste = [1,2,3]

In [5]:
liste

[1, 2, 3]

In [6]:
liste += 1

TypeError: 'int' object is not iterable

In [7]:
import numpy as np

In [8]:
liste2 = np.array(liste)
liste2 += 1

In [9]:
liste2

array([2, 3, 4])

In [10]:
liste2 = np.array(liste)
liste2 += 5

In [11]:
liste2

array([6, 7, 8])

In [13]:
liste2*5

array([30, 35, 40])