In [1]:
import numpy as np

In [4]:
matris = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
matris.size

9

In [6]:
matris.ndim

2

In [7]:
matris.shape

(3, 3)

In [9]:
matris[0,0]

1

In [10]:
matris[2,2]

9

In [11]:
matris[1,2]

6

In [16]:
matris[:,]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
matris[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [19]:
matris[:,1:2]

array([[2],
       [5],
       [8]])

In [20]:
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
matris[2,1] = 35

In [23]:
matris

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 35,  9]])