In [1]:
import numpy as np

In [2]:
np.linspace(0,10,5) #0'dan 10'a kadar olan aralıkta 5 farklı sayı verir.
                    #Sayılar arasındaki fark eşittir.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
np.linspace(3,29,7)

array([ 3.        ,  7.33333333, 11.66666667, 16.        , 20.33333333,
       24.66666667, 29.        ])

In [7]:
dizi = np.array(["a","b"])
dizi2 = np.array(["a","b"])
dizi3 = np.array([1,2])
dizi4 = np.array(["a",2])

In [5]:
dizi == dizi2

array([ True,  True])

In [6]:
dizi == dizi3

<ipython-input-6-d9d2d41384ba>:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  dizi == dizi3


False

In [8]:
dizi == dizi4

array([ True, False])

In [9]:
dizi != dizi4

array([False,  True])

In [10]:
d1 = np.array([1,2])
d2 = np.array([0,5])

In [11]:
d1 < d2

array([False,  True])