In [1]:
liste = [1,2,3,"4"]

In [7]:
liste

[1, 2, 3, '4']

In [2]:
type(liste)

list

In [4]:
import numpy as np

In [5]:
dizi = np.array(liste)

In [6]:
dizi

array(['1', '2', '3', '4'], dtype='<U11')

In [8]:
type(dizi)

numpy.ndarray

In [9]:
dizi.shape

(4,)

In [10]:
dizi.ndim

1

In [13]:
liste2 = ([1,2],[3,4])

In [14]:
liste2

([1, 2], [3, 4])

In [15]:
type(liste2)

tuple

In [16]:
dizi2 = np.array(liste2)
dizi2

array([[1, 2],
       [3, 4]])

In [17]:
dizi2.ndim

2

In [18]:
dizi2.shape

(2, 2)

In [25]:
dizi2.fill(5)

In [26]:
dizi2

array([[5, 5],
       [5, 5]])

In [27]:
dizi2.fill("5")

In [28]:
dizi2

array([[5, 5],
       [5, 5]])