In [1]:
import numpy as np

In [2]:
dizi = np.arange(5)

In [3]:
dizi

array([0, 1, 2, 3, 4])

In [5]:
dizi.shape

(5,)

In [8]:
dizi2 = np.array(([[0, 1, 2, 3, 4, 5]]))
dizi2

array([[0, 1, 2, 3, 4, 5]])

In [9]:
dizi2.shape

(1, 6)

In [10]:
dizi2.shape = 3,2

In [11]:
dizi2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
dizi2.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
dizi2.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [15]:
matris = np.array([[1,2,3],[4,5,6],[7,8,9]])
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
matris.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [17]:
matris2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
matris2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [18]:
matris3 = np.concatenate((matris,matris2))
matris3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [19]:
matris4 = np.concatenate((matris,matris2), axis = 1)
matris4

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60],
       [ 7,  8,  9, 70, 80, 90]])

In [20]:
np.vstack((matris,matris2)) #vertical : dikey

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
np.hstack((matris,matris2)) #horizontal : yatay

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60],
       [ 7,  8,  9, 70, 80, 90]])