In [1]:
import numpy as np

In [2]:
dizi = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
dizi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
dizi.min()

1

In [4]:
dizi.max()

9

In [5]:
dizi.argmin() #Bir fonksiyonun min noktası. Dizi'nin min noktası

0

In [7]:
dizi.sum()

45

In [9]:
ortalama = 45/9

In [10]:
ortalama

5.0

In [11]:
dizi.mean()

5.0

In [12]:
dizi.mean(axis=0) #Her kolonun ortalaması

array([4., 5., 6.])

In [13]:
dizi.mean(axis=1) #Her satırın ortalaması

array([2., 5., 8.])

In [14]:
dizi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
dizi.std()

2.581988897471611

In [16]:
dizi.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [17]:
dizi.var()

6.666666666666667

In [18]:
dizi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
dizi.clip(2,5) #Sadece istenilen 2 değer arasındaki değerler kalır, diğerleri
               #o değerlere dönüşür.

array([[2, 2, 3],
       [4, 5, 5],
       [5, 5, 5]])

In [22]:
dizi2 = np.random.rand(3,3)*10

In [23]:
dizi2

array([[5.97817069, 4.18328823, 1.67989435],
       [9.45486288, 6.96231344, 6.72294806],
       [8.66637353, 3.01226023, 7.56781391]])

In [24]:
dizi2.round()

array([[6., 4., 2.],
       [9., 7., 7.],
       [9., 3., 8.]])

In [26]:
dizi2 = dizi2.round()
dizi2

array([[6., 4., 2.],
       [9., 7., 7.],
       [9., 3., 8.]])

In [27]:
dizi3 = np.random.rand(3,3)*10

In [28]:
dizi3

array([[6.51439185, 7.31680076, 9.42594366],
       [7.4214956 , 1.6300583 , 3.01114629],
       [1.84218099, 1.20389511, 5.73867332]])

In [29]:
dizi3.round(decimals=2)

array([[6.51, 7.32, 9.43],
       [7.42, 1.63, 3.01],
       [1.84, 1.2 , 5.74]])