In [1]:
import numpy as np

In [2]:
dizi = np.array([[5,15,25],[35,45,55]])
dizi

array([[ 5, 15, 25],
       [35, 45, 55]])

In [3]:
np.sum(dizi)

180

In [4]:
np.prod(dizi)

162421875

In [5]:
np.sum(dizi, axis=1)
# 5,15,25 >>> 5+15+25 = 45
# 35,45,55 >>> 35+45+55 =135

array([ 45, 135])

In [6]:
np.prod(dizi, axis = 1)
# 5,15,25 >>> 5x15x25 = 1875
# 35,45,55 >>> 35x45x55 = 86625

array([ 1875, 86625])

In [7]:
5*15*25

1875

In [8]:
dizi

array([[ 5, 15, 25],
       [35, 45, 55]])

In [10]:
np.sum(dizi, axis=0)

array([40, 60, 80])

In [11]:
np.prod(dizi, axis=0)

array([ 175,  675, 1375])